### ISSUE TITLE
[Feature] About the directory to save checkpoints and cfg file

### ISSUE THREAD

**Issue by JunweiZheng93** [open-mmlab/mmengine#1060]
### What is the feature?

MMEngie is amazing. I noticed the cfg file saved by the Runner and ckpts saved by the CheckpointHook are under the `work_dirs`.  I think it will make more sense if they are saved under the `work_dirs/timestamp`. The reason is when we want to rerun the same experiment, the old cfg file and ckpts will be overwritten. The cfg file and ckpts are experiment-relevant stuff, so it will be nicer if they are saved under `work_dirs/timestamp`.

**Comment by zhouzaida** [comment]
Hi @JunweiZheng93 , thanks for your feedback. The [work_dir](https://github.com/open-mmlab/mmengine/blob/8bf1ecad3868204ce5b6a07cd324173bedbaa2e8/mmengine/runner/runner.py#L246) is usually set as a separate directory for each configuration, for example, if the original configuration file is named faster.py, it is recommended to set its work_dir as 'work_dir/faster'. When you modify the configuration of faster.py, such as changing the learning rate (lr), you can set the work_dir as 'work_dir/faster_lr_0.5', which allows you to distinguish different experiments instead of relying on timestamps.

**Comment by JunweiZheng93** [comment]
Hi @zhouzaida , thx for your kind explanation. I agree `work_dir` should be used in the way you mentioned. Actually, I also use it in such a way. If I want to run the exact same experiment twice (in order to get a better final result), the outcomes (including cfg_file and ckpt_file) of the newer one will overwrite the older one, right? I know I can change the experiment name, but it would be great if the outcomes could be saved under different timestamps within the same experiment name.

By the way, would you mind giving me some explanation on the design motivation of the timestamp? Thx.

**Comment by zhouzaida** [comment]
Using the timestamp as the directory name was not a well-considered decision. The reason why the checkpoint (ckpt) files were not placed in the timestamp directory was that the original plan was to support automatic training recovery by iterating through the ckpt files in the current directory (e.g., the ckpt with the highest epoch). However, this method of implementing the automatic recovery feature was replaced by [latest_checkpoint](https://github.com/open-mmlab/mmengine/blob/f76218a4895e33b9993df507d3996b9aa92f0660/mmengine/runner/runner.py#L1639) through a latest_checkpoint file.

**Comment by JunweiZheng93** [comment]
Okay, I respect the design. It is actually a very personal preference where to store the outcomes. I will implement my own Runner and CheckpointHook to meet my need. Close.
