### ISSUE TITLE
[Feature] Inappropriate default "mp_start_method=fork"

### ISSUE THREAD

**Issue by jiaxiaosong1002** [open-mmlab/mmengine#1145]
### What is the feature?

Set the default "mp_start_method" in mmengine.utils.dl_utils.setup.py to "spawn". Do not set "XX_NUM_THREADS" to 1.

Change the  mp_cfg=dict(mp_start_method='fork') in all tutorials to "spawn".

I have tried to migrate my code from mmcv 1.x to mmengine + mmcv 2.0. I noticed a significant slow down (10x ~ 100x) in data prerprocessing, which becomes the bottleneck of training.

After benchmarking each steps, **I find that those pipelines/transforms with dense numpy operation would be slow down by 10x or 100x. It might be becuase numpy is unable to use multi-threads due to "fork"** (Not sure why).

The reason why I find the multiprocessing might be the problem is that when I use "num_worker=0" (no new subprocess for data loading) all the numpy related issues are gone while use "num_worker=1" (a seperate subprocess for data loading) could be very slow.

**Comment by HAOCHENYE** [comment]
Thank you for your feedback. the current code implementation can be traced back to this [PR](https://github.com/open-mmlab/mmdetection/pull/6867), which includes detailed experimental configurations and performance comparisons.

I thinks that the core problem for your program is that the **dense numpy operation** need to be accelerated by multi-thread parallel, however, which is disabled by our default behavior. I suggest you setting `env_cfg=dict(mp_cfg=dict(opencv_num_threads=4))` for the `Runner`, maybe it can help you to accelerate the numpy operations.

**Comment by jiaxiaosong1002** [comment]
No, it does not at all. I have tried to set opencv_num_threads to 1, 2, 4, 8, 16, 32. Also, the variables "MKL_NUM_THREADS", "OMP_NUM_THREADS", "MPI_NUM_THREADS", and "OPENBLAS_NUM_THREADS". **It does not help at all.**


  In fact, I have figured out the reason. It might be related to the "thread-lock", for which "spawn" and "fork" have very distinct behaviors https://stackoverflow.com/questions/64095876/multiprocessing-fork-vs-spawn.  Please find someone with a  **really deep understanding** to handle the issue. Thanks!

**Comment by HAOCHENYE** [comment]
Alright, let us dive into this issue deeper, when we decide to use `fork` rather than `fork`, we also noticed that there is a warning of PyTorch API [document](https://pytorch.org/docs/stable/notes/multiprocessing.html#multiprocessing-best-practices):

![image](https://github.com/open-mmlab/mmengine/assets/57566630/3eee7c57-b20a-48f4-921e-acc7fe94d87b)

And you can found more details information [here](
![image](https://github.com/open-mmlab/mmengine/assets/57566630/0bdd5109-1f10-4269-911e-c3b6a2cc356c)
):

![image](https://github.com/open-mmlab/mmengine/assets/57566630/d12decdb-aa1e-438d-9b76-8bb580f1f53c)

If you are interested in it, you'll find that the **dead lock** is caused by the forked subprocess with an inherited lock and thread. Therefore, PyTorch official suggest using `spawn` rather than `fork` to create a subprocess. However, looking back at the deep learning pipeline, the subprocess will be created in two places (in most cases):

1. `launch` function of ddp training
2. multiple workers in dataloader for prefetching data.

In most cases, the subprocess created by `launch` and the workers created by `Dataloader` will not trigger the dead-lock or lock contention (maybe the reason for performance degradation ).

In your case, I guess the dataset you created has some attributes which lead to the workers created in Dataloader inheriting some contended resources. Maybe it is not caused by your code, but caused by other third-party python packages.

I can provide you the simplest example to explain why dead-lock could happen:

```
import multiprocessing
import threading
import time

lock = threading.Lock()


def g():
    print('start')
    lock.acquire()
    time.sleep(1)
    print('end')
    lock.release()


if __name__ == '__main__':
    # change `fork` to `spawn`, then dead lock will not happen
    multiprocessing.set_start_method('fork')

    t = threading.Thread(target=g)
    p = multiprocessing.Process(target=g)
    t.start()
    p.start()
```
 If this kind of code in your code or other python packages (maybe not the dead lock case), your training speed will also be influenced. 

Anyway, If you really want to figure out what is the main reason for slowing down the training, you can provide a simple minimum example for us to help locate the issue. We're not sure if the decisions made at that time align with the trends in deep learning development. If it is a commen case currently, we would consider switching from `fork` to `spawn`.
