### ISSUE TITLE
[Docs] Add "colossalai" in requirements 

### ISSUE THREAD

**Issue by Yanjia0** [open-mmlab/mmengine#1487]
### 📚 The doc issue

Hi developers, thank you so much for integrating with Colossal-AI~
Could you please add "colossalai" in "requirements.txt"?
Thank you! If you need any help when using Colossal-AI, feel free to join our Slack/Wechat group~

**Comment by fanqiNO1** [comment]
Hello, thank you very much for your suggestion. Since Strategy including `DeepspeedStrategy` and `ColossalAIStrategy` are not used in general usage scenarios of mmengine, but only when using Flexible Runner with Strategy, adding them directly to the requirements will result in a more complex and time-consuming installation of mmengine in general usage scenarios. Therefore, we did not add relevant dependencies to the requirements. We prefer that the users install the corresponding dependencies themselves when using `DeepSpeedStrategy` or `ColossalAIStrategy`.

For installing and using the `DeepSpeedStrategy` and `ColossalAIStrategy` sections, you can refer to https://mmengine.readthedocs.io/en/latest/common_usage/large_model_training.html
