### ISSUE TITLE
How does the add_graph func work?

### ISSUE THREAD

**Issue by shenmishajing** [open-mmlab/mmengine#621]
The func add_graph of vis_backend is not called now. It has two parameters model and data_batch, which may indicate that it should be called every iter? But vis_backend like wandb will draw the model without data_batch and should be called only once. Therefore, should we delete the data_batch input of add_graph func? If yes, I will create a pr to do this and fix the add_graph func is not called bug.

**Comment by HAOCHENYE** [comment]
Thannnnks for your feedback！ We want to draw the model in tensorboard initially, and tensorboard require `data_batch` and `model`  arguments. Since the visualization result in tensorboard is unattractive and more restrictive, we've not integrated `add_graph` in hooks now(implemented in `before_run` is acceptable).

I'm not familiar with wandb, can wandb plot the model graph without tracing the model(without data_batch)?

**Comment by shenmishajing** [comment]
Yes, wandb can do this by wandb.watch. it works without `data_batch`, by hook. But, if you mean plot a png file which pictures the relationship between modules of your model by "plot the model", then the answer is no, hhhhh.

I try to add this feature into mmengine, but the log graph does not work now, so I find some result on web. See here https://wandb.ai/ayush-thakur/debug-neural-nets/runs/jh061uaf/model wandb will get the input and output of every modules in your model, which is unattractive too, I think.

In fact, the useful point of wandb.watch is it can log the disturibution of gradients and parameters of your model during training, which is usefull if your want to know is any gradient flow bottleneck in your model and will help you to redesign your network architecture.

Here is a log result(an experiment I just run about 2000 iter, gradients and parameters do not change a lot).
<img width="1804" alt="截屏2022-10-17 19 33 02" src="https://user-images.githubusercontent.com/32559715/196166746-1c9977ba-c7e5-402e-b6de-7940d87ebd53.png">

**Comment by HAOCHENYE** [comment]
Wow! the weight&gradient distribution displayed by wandb seems so cool 😎! I think this feature should be integrated with `WandbVisBackend.add_graph`, and called by `NativeVisualizationHook.before_train` (model weight distribution graph and model topology graph are both graph 🤣). 

We should still keep the `data_batch` arguments since other backends need the input tensor to trace the whole model (Although `wandb.watch` utilize the backward_fn to reconstruct the graph, but utilizing the input tensor maybe could trace the graph prettier 🤔 ) .

We may invite @hhaAndroid to have a look if it is reasonable to call `add_graph` in `NativeVisualizationHook.before_train`. If reasonable, I think this cool feature could be integrated into MMEngine.
